version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17        
      python: 3.11
    commands:
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip install -r $CODEBUILD_SRC_DIR/requirements.txt pylint
      - python --version
  pre_build:
    commands:
  build:
    commands:
artifacts:
  files:
    - '**/*'